#include<stdio.h>
#include <stdlib.h> 
#include <time.h> 
#include<conio.h>

int input() {

	while (_kbhit()) {
		_getch();
	}

	return _getch();

}

int main(void) {

	const int lnnum = 13;

	char golf[lnnum][5000] = {
		"//これは何の言語でしょう？\nmain(){puts(\"HelloWorld\");}",
		"これは何の言語でしょう？\n>+++++++++[<++++++++>-]<.>+++++++[<++++>-]<+.+++++++..+++.[-]>++++++++[<++++>-]<.>++++++++++ + [<++++ + >-]<.>++++++++[<++ + >-]<.++ + .------.--------.[-]>++++++++[<++++>-]<+.[-]++++++++++.",
		"/*これは何の言語でしょう？*/\nn;z;B;main(T){i=T;z=T++;n=z*z*z;B=n;putchar(n*T*T);n=n*n+n*(n-T)-z-i;putchar(n);n+=B-i;putchar(n);putchar(n);n+=z+i;putchar(n);putchar(n-B-B-B);putchar(n);putchar(n+T);n-=i+z;putchar(n);putchar(n-B);}",
		"これは何の言語でしょう？\n ",
		"//これは何の言語でしょう？\n#include<iostream.h>\nmain(){cout<<\"Hello world!\"<<endl;}",
		"これは何の言語でしょう？\nH",
		"これは何の言語でしょう？\n\\s\\s\\s\\t\\s\\s\\t\\s\\s\\s\n\\t\n\\s\\s\\s\\s\\s\\t\\t\\s\\s\\t\\s\\t\n\\t\n\\s\\s\\s\\s\\s\\t\\t\\s\\t\\t\\s\\s\n\\s\n\\s\\s\n\\s\\t\n\\s\\s\\t\n\\s\\s\\s\\s\\s\\t\\t\\s\\t\\t\\t\\t\n\\s\n\\s\\t\n\\s\\s\\s\\s\\s\\s\\t\\s\\s\\s\\s\\s\n\\t\n\\s\\s\\s\\s\\s\\t\\s\\t\\s\\t\\t\\t\n\\t\n\\s\\s\\t\n\\s\\s\\s\\s\\s\\t\\t\\t\\s\\s\\t\\s\n\\t\n\\s\\s\\t\n\\s\\s\\s\\s\\s\\t\\t\\s\\s\\t\\s\\s\n\\t\n\\s\\s\\s\\s\\s\\s\\t\\s\\s\\s\\s\\t\n\\t\n\\s\\s\n\n\n\n",
		"これは何の言語でしょう？\nOok.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook!Ook?Ook.Ook?Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook?Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook?Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook?Ook.Ook?Ook.Ook?Ook.Ook!Ook!Ook?Ook!Ook.Ook?Ook!Ook.Ook.Ook?Ook.Ook.Ook.Ook.Ook!Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook!Ook.Ook!Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook!Ook.Ook.Ook?Ook!Ook!Ook!Ook.Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook.Ook?Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook!Ook.Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook.Ook.Ook.Ook.Ook.Ook.Ook.Ook!Ook.Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook.Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook!Ook.Ook.Ook?Ook.Ook.Ook!Ook.",
		"Daivid Morgan Mar作の抽象画を描くようにプログラミングが出来る言語は？",
		"料理を作るレシピのようなプログラミング言語は？",
		"悪の魔術師のために作られた言語は？",
		"これは何の言語でしょう？\nLINENUMBERZEROCODEPRINTZEROGOTOONEONEZEROONELINENUMBERONECODEPRINTZEROGOTOONEZEROLINENUMBERONEONECODEPRINTZEROGOTOONEZEROZEROONEZEROLINENUMBERONEZEROCODEPRINTONEGOTOONEONELINENUMBERONEONEONECODEPRINTONEGOTOONEZEROONELINENUMBERONEZEROONECODEPRINTZEROGOTOONEONEZEROLINENUMBERONEONEZEROCODEPRINTONEGOTOONEZEROZEROLINENUMBERONEZEROZEROCODEPRINTONEGOTOONEONEONEONELINENUMBERONEONEONEONECODEPRINTZEROGOTOONEZEROONEONELINENUMBERONEZEROONEONECODEPRINTZEROGOTOVARIABLEONELINENUMBERONEONEZEROONECODEPRINTONEGOTOONEONEONEZEROLINENUMBERONEONEONEZEROCODEPRINTZEROGOTOONEZEROZEROONELINENUMBERONEZEROZEROONECODEPRINTZEROGOTOONEZEROONEZEROLINENUMBERONEZEROONEZEROCODEPRINTONEGOTOONEONEZEROZEROLINENUMBERONEONEZEROZEROCODEPRINTZEROGOTOONEZEROZEROZEROLINENUMBERONEZEROZEROZEROCODEPRINTZEROGOTOONEONEONEONEONELINENUMBERONEONEONEONEONECODEPRINTZEROGOTOONEZEROONEONEONELINENUMBERONEZEROONEONEONECODEPRINTZEROGOTOONEONEZEROONEONELINENUMBERONEONEZEROONEONECODEPRINTONEGOTOONEONEONEZEROONELINENUMBERONEONEONEZEROONECODEPRINTONEGOTOONEONEONEONEZEROLINENUMBERONEONEONEONEZEROCODEPRINTZEROGOTOONEZEROZEROONEONELINENUMBERONEZEROZEROONEONECODEPRINTZEROGOTOONEZEROONEZEROONELINENUMBERONEZEROONEZEROONECODEPRINTONEGOTOONEZEROONEONEZEROLINENUMBERONEZEROONEONEZEROCODEPRINTZEROGOTOONEONEZEROZEROONELINENUMBERONEONEZEROZEROONECODEPRINTONEGOTOONEONEZEROONEZEROLINENUMBERONEONEZEROONEZEROCODEVARIABLEONEEQUALSONEONEONEZEROZEROGOTOONELINENUMBERONEONEONEZEROZEROCODEVARIABLEONEEQUALSONEZEROZEROZEROONEGOTOONELINENUMBERONEZEROZEROZEROONECODEVARIABLEONEEQUALSONEONEONEONEZEROONEGOTOONEONELINENUMBERONEZEROZEROONEZEROCODEPRINTONEGOTOONEZEROONEZEROZEROLINENUMBERONEZEROONEZEROZEROCODEPRINTONEGOTOONEONEZEROZEROZEROLINENUMBERONEONEZEROZEROZEROCODEPRINTZEROGOTOONEZEROZEROZEROZEROLINENUMBERONEZEROZEROZEROZEROCODEPRINTONEGOTOONEONEONEONEONEONELINENUMBERONEONEONEONEONEONECODEPRINTONEGOTOONEZEROONEONEONEONELINENUMBERONEZEROONEONEONEONECODEPRINTONEGOTOONEONEZEROONEONEONELINENUMBERONEONEZEROONEONEONECODEPRINTONEGOTOONEONEONEZEROONEONELINENUMBERONEONEONEZEROONEONECODEPRINTZEROGOTOVARIABLEONELINENUMBERONEONEONEONEZEROONECODEPRINTZEROGOTOONEONEONEONEONEZEROLINENUMBERONEONEONEONEONEZEROCODEPRINTZEROGOTOONEZEROZEROONEONEONELINENUMBERONEZEROZEROONEONEONECODEPRINTONEGOTOONEZEROONEZEROONEONELINENUMBERONEZEROONEZEROONEONECODEPRINTZEROGOTOONEZEROONEONEZEROONELINENUMBERONEZEROONEONEZEROONECODEPRINTZEROGOTOONEZEROONEONEONEZEROLINENUMBERONEZEROONEONEONEZEROCODEPRINTZEROGOTOONEONEZEROZEROONEONELINENUMBERONEONEZEROZEROONEONECODEPRINTZEROGOTOONEONEZEROONEZEROONELINENUMBERONEONEZEROONEZEROONECODEPRINTZEROGOTOONEONEZEROONEONEZEROLINENUMBERONEONEZEROONEONEZEROCODEPRINTZEROGOTOONEONEONEZEROZEROONELINENUMBERONEONEONEZEROZEROONECODEPRINTONEGOTOONEONEONEZEROONEZEROLINENUMBERONEONEONEZEROONEZEROCODEPRINTONEGOTOONEONEONEONEZEROZEROLINENUMBERONEONEONEONEZEROZEROCODEPRINTONEGOTOONEZEROZEROZEROONEONELINENUMBERONEZEROZEROZEROONEONECODEPRINTZEROGOTOONEZEROZEROONEZEROONELINENUMBERONEZEROZEROONEZEROONECODEPRINTONEGOTOONEZEROZEROONEONEZEROLINENUMBERONEZEROZEROONEONEZEROCODEPRINTONEGOTOONEZEROONEZEROZEROONELINENUMBERONEZEROONEZEROZEROONECODEPRINTONEGOTOONEZEROONEZEROONEZEROLINENUMBERONEZEROONEZEROONEZEROCODEVARIABLEONEEQUALSONEZEROONEONEZEROZEROGOTOONEONELINENUMBERONEZEROONEONEZEROZEROCODEPRINTZEROGOTOONEONEZEROZEROZEROONELINENUMBERONEONEZEROZEROZEROONECODEPRINTONEGOTOONEONEZEROZEROONEZEROLINENUMBERONEONEZEROZEROONEZEROCODEPRINTONEGOTOONEONEZEROONEZEROZEROLINENUMBERONEONEZEROONEZEROZEROCODEPRINTONEGOTOONEONEONEZEROZEROZEROLINENUMBERONEONEONEZEROZEROZEROCODEPRINTZEROGOTOONEZEROZEROZEROZEROONELINENUMBERONEZEROZEROZEROZEROONECODEPRINTZEROGOTOONEZEROZEROZEROONEZEROLINENUMBERONEZEROZEROZEROONEZEROCODEPRINTONEGOTOONEZEROZEROONEZEROZEROLINENUMBERONEZEROZEROONEZEROZEROCODEPRINTZEROGOTOONEZEROONEZEROZEROZEROLINENUMBERONEZEROONEZEROZEROZEROCODEVARIABLEONEEQUALSONEONEZEROZEROZEROZEROGOTOONELINENUMBERONEONEZEROZEROZEROZEROCODEPRINTZEROGOTOONEONEONEONEONEONEONELINENUMBERONEONEONEONEONEONEONECODEPRINTONEGOTOONEZEROZEROZEROZEROZEROLINENUMBERONEZEROZEROZEROZEROZEROCODEPRINTONEGOTOONEZEROONEONEONEONEONELINENUMBERONEZEROONEONEONEONEONECODEPRINTZEROGOTOONEONEZEROONEONEONEONELINENUMBERONEONEZEROONEONEONEONECODEPRINTZEROGOTOONEONEONEZEROONEONEONELINENUMBERONEONEONEZEROONEONEONECODEPRINTONEGOTOONEONEONEONEZEROONEONELINENUMBERONEONEONEONEZEROONEONECODEPRINTZEROGOTOONEONEONEONEONEZEROONELINENUMBERONEONEONEONEONEZEROONECODEPRINTZEROGOTOONEONEONEONEONEONEZEROLINENUMBERONEONEONEONEONEONEZEROCODEPRINTZEROGOTOONEZEROZEROONEONEONEONELINENUMBERONEZEROZEROONEONEONEONECODEPRINTZEROGOTOONEZEROONEZEROONEONEONELINENUMBERONEZEROONEZEROONEONEONECODEPRINTONEGOTOONEZEROONEONEZEROONEONELINENUMBERONEZEROONEONEZEROONEONECODEPRINTZEROGOTOONEZEROONEONEONEZEROONELINENUMBERONEZEROONEONEONEZEROONECODEPRINTZEROGOTOONEZEROONEONEONEONEZEROLINENUMBERONEZEROONEONEONEONEZEROCODEPRINTZEROGOTOONEONEZEROZEROONEONEONELINENUMBERONEONEZEROZEROONEONEONECODEPRINTZEROGOTOONEONEZEROONEZEROONEONELINENUMBERONEONEZEROONEZEROONEONECODEPRINTONE",
		"これは何の言語でしょう？\n(=<`:9876Z4321UT.-Q+*)M'&%$H\"!~} | Bzy ? = | {z]KwZY44Eq0 / {mlk**hKs_dG5[m_BA{ ? -Y;; Vb'rR5431M}/.zHGwEDCBA@98\\6543/.R,+O<",
	};

		char ans[lnnum][1000] = {		
		"C",
		"Brainfuck",
		"C",
		"BrainCrash",
		"C++",
		"HQ9+",
		"Whitespace",
		"Ook!",
		"Piet",
		"Chef",
		"ZOMBIE",
		"BIT",
		"Malbolge",
	};


	unsigned int now = (unsigned int)time(0);
	srand(now); rand(); rand(); rand(); rand(); rand();

	bool already[lnnum] = { 0 };
	bool tf = 1;

	int i = 0, j = 0, alnum = 0, result = 0;
	char user[1000] = { 0 };

	while (alnum < lnnum) {
		i = rand() % lnnum;

		if (already[i] == 0) {
			printf("第%d問(全%d問)",++alnum,lnnum);
			puts(golf[i]);
			already[i] = 1;
			puts("正確に入力してください．バージョン名は不要です．Enterキーで決定です．");
			fgets(user, 1000, stdin);

			tf = 1;

			for (j = 0; ans[i][j]; j++) {
				if (ans[i][j] != user[j]) {
					tf = 0;
					while (user[j++])user[j] = 0; break;
				}
				user[j] = 0;
			}
			if (user[j] != '\n')tf = 0;
			if (tf)puts("正解です"), result++;
			else {
				puts("不正解です"), result--; 
				printf("正解は%sです\n",ans[i]);
			}
		}
	}

	puts("\n-結果発表-"); printf("あなたの言語愛度は %d です．",result);
	if (result < 0)puts("もう少し頑張りましょう");
	else if (!result)puts("可もなく不可もなくですね");
	else if (result < lnnum)puts("友達になってください");
	else puts("全問正解です．問題を追加してみませんか？");


	input();

	return 0;
}